from models.types import Type

TYPE_EFFECTIVENESS = {
    Type.NORMAL: {
        Type.ROCK: 0.5,
        Type.GHOST: 0,
        Type.STEEL: 0.5,
    },
    Type.FIGHTING: {
        Type.NORMAL: 2.0,
        Type.FLYING: 0.5,
        Type.POISON: 0.5,
        Type.ROCK: 2.0,
        Type.BUG: 0.5,
        Type.GHOST: 0.0,
        Type.STEEL: 2.0,
        Type.PSYCHIC: 0.5,
        Type.ICE: 2.0,
        Type.DARK: 2.0,
        Type.FAIRY: 0.5,
    },
    Type.FLYING: {
        Type.FIGHTING: 2.0,
        Type.ROCK: 0.5,
        Type.BUG: 2.0,
        Type.STEEL: 0.5,
        Type.GRASS: 2.0,
        Type.ELECTRIC: 0.5,
    },
    Type.POISON: {
        Type.POISON: 0.5,
        Type.GROUND: 0.5,
        Type.ROCK: 0.5,
        Type.GHOST: 0.5,
        Type.STEEL: 0.0,
        Type.GRASS: 2.0,
        Type.FAIRY: 2.0,
    },
    Type.GROUND: {
        Type.FLYING: 0.0,
        Type.POISON: 2.0,
        Type.ROCK: 2.0,
        Type.BUG: 0.5,
        Type.STEEL: 2.0,
        Type.FIRE: 2.0,
        Type.GRASS: 0.5,
        Type.ELECTRIC: 2.0,
    },
    Type.ROCK: {
        Type.FIGHTING: 0.5,
        Type.FLYING: 2.0,
        Type.GROUND: 0.5,
        Type.BUG: 2.0,
        Type.STEEL: 0.5,
        Type.FIRE: 2.0,
        Type.ICE: 2.0,
    },
    Type.BUG: {
        Type.FIGHTING: 0.5,
        Type.FLYING: 0.5,
        Type.POISON: 0.5,
        Type.GHOST: 0.5,
        Type.STEEL: 0.5,
        Type.FIRE: 0.5,
        Type.GRASS: 2.0,
        Type.PSYCHIC: 2.0,
        Type.DARK: 2.0,
        Type.FAIRY: 0.5,
    },
    Type.GHOST: {
        Type.NORMAL: 0.0,
        Type.GHOST: 2.0,
        Type.PSYCHIC: 2.0,
        Type.DARK: 0.5,
    },
    Type.STEEL: {
        Type.ROCK: 2.0,
        Type.STEEL: 0.5,
        Type.FIRE: 0.5,
        Type.WATER: 0.5,
        Type.ELECTRIC: 0.5,
        Type.ICE: 2.0,
        Type.FAIRY: 2.0,
    },
    Type.FIRE: {
        Type.FIRE: 0.5,
        Type.ROCK: 0.5,
        Type.WATER: 0.5,
        Type.DRAGON: 0.5,
        Type.GRASS: 2.0,
        Type.STEEL: 2.0,
        Type.ICE: 2.0,
        Type.BUG: 2.0,
    },
    Type.WATER: {
        Type.GROUND: 2.0,
        Type.ROCK: 2.0,
        Type.FIRE: 2.0,
        Type.WATER: 0.5,
        Type.GRASS: 0.5,
        Type.DRAGON: 0.5,
    },
    Type.GRASS: {
        Type.GRASS: 0.5,
        Type.FIRE: 0.5,
        Type.BUG: 0.5,
        Type.DRAGON: 0.5,
        Type.STEEL: 0.5,
        Type.FLYING: 0.5,
        Type.POISON: 0.5,
        Type.GROUND: 2.0,
        Type.ROCK: 2.0,
        Type.WATER: 2.0,
    },
    Type.ELECTRIC: {
        Type.FLYING: 2.0,
        Type.GROUND: 0.0,
        Type.WATER: 2.0,
        Type.GRASS: 0.5,
        Type.ELECTRIC: 0.5,
        Type.DRAGON: 0.5,
    },
    Type.PSYCHIC: {
        Type.FIGHTING: 2.0,
        Type.POISON: 2.0,
        Type.STEEL: 0.5,
        Type.PSYCHIC: 0.5,
        Type.DARK: 0.0,
    },
    Type.ICE: {
        Type.FLYING: 2.0,
        Type.GROUND: 2.0,
        Type.STEEL: 0.5,
        Type.FIRE: 0.5,
        Type.WATER: 0.5,
        Type.GRASS: 2.0,
        Type.ICE: 0.5,
        Type.DRAGON: 2.0,
    },
    Type.DRAGON: {
        Type.STEEL: 0.5,
        Type.DRAGON: 2.0,
        Type.FAIRY: 0.0,
    },
    Type.DARK: {
        Type.FIGHTING: 0.5,
        Type.GHOST: 2.0,
        Type.PSYCHIC: 2.0,
        Type.DARK: 0.5,
        Type.FAIRY: 0.5,
    },
    Type.FAIRY: {
        Type.FIGHTING: 2.0,
        Type.POISON: 0.5,
        Type.STEEL: 0.5,
        Type.FIRE: 0.5,
        Type.ICE: 2.0,
        Type.DRAGON: 2.0,
    }
}

