name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --tb=short --cov=src/models --cov-report=term
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --tb=short --cov=src/models --cov-append --cov-report=term
    - name: Run legacy tests (if any)
      run: |
        if [ -d "tests" ] && [ "$(find tests -maxdepth 1 -name "test_*.py" -type f | wc -l)" -gt 0 ]; then
          pytest tests/test_*.py -v --tb=short
        else
          echo "No legacy tests found"
        fi
